### ISSUE TITLE
array index out of range error when pattern doesn't match

### ISSUE THREAD

**Issue by twk3** [dropseed/deps-git#3]
If you use a pattern that doesn't match anything in the file, you get an unclear error .

```sh
panic: runtime error: index out of range

goroutine 1 [running]:
main.collect(0x7ffea4e3bd4a, 0x1, 0x7ffea4e3bd4c, 0x13, 0x7)
	/home/travis/gopath/src/github.com/dropseed/deps-git/collect.go:28 +0x883
main.main()
	/home/travis/gopath/src/github.com/dropseed/deps-git/main.go:24 +0x20a
```

https://github.com/dropseed/deps-git/blob/87a51bd98f98d0d0c7456762cb5d9e5fab067470/collect.go#L28

**Comment by davegaeddert** [comment]
Good point. It will still do an ugly panic (which I'd like to clean up later) but I at least gave it more informative output for now:
```sh
panic: Pattern not found in file

  Pattern: minikube versiond (\S+)
  Filename: file.txt

goroutine 1 [running]:
main.collect(0x7ffeefbff863, 0x1, 0x7ffeefbff865, 0x3f, 0x0)
	/Users/davegaeddert/Development/go/src/github.com/dropseed/deps-git/collect.go:29 +0xa69
main.main()
	/Users/davegaeddert/Development/go/src/github.com/dropseed/deps-git/main.go:24 +0x277
```

Fixed in f82d4398017b280c2582eac3ef1c380ea90b202c
